In [1]:
import os

os.getcwd()
os.chdir("C:/Users/R. K Bokul/Desktop/Project_Face_Recognition")

from tensorflow import keras
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense, Dropout, BatchNormalization
from keras.optimizers import SGD, Adam
from keras.constraints import maxnorm
from keras import regularizers
from sklearn.metrics import classification_report
from sklearn import metrics
import numpy as np

In [2]:
# Initialising the CNN
Model = Sequential()

In [3]:
# Step 1 - Convolution
Model.add(Conv2D(32, (3, 3), padding="same", input_shape = (64, 64, 3), activation = 'relu'))
Model.add(BatchNormalization())

# Step 2 - Pooling
Model.add(MaxPooling2D(pool_size = (2, 2)))

# Adding a second convolutional layer
Model.add(Conv2D(64, (3, 3), padding="same", activation = 'relu'))
Model.add(BatchNormalization())
Model.add(Dropout(0.1))
Model.add(MaxPooling2D(pool_size = (2, 2)))

# Adding a third convolutional layer
Model.add(Conv2D(128, (3, 3), padding="same", activation = 'relu'))
Model.add(BatchNormalization())
Model.add(Dropout(0.2))
Model.add(MaxPooling2D(pool_size = (2, 2)))

# Step 3 - Flattening
Model.add(Flatten())

# Step 4 - Full connection
Model.add(Dense(units = 50, activation = 'relu', kernel_regularizer=regularizers.l2(0.0001)))
Model.add(Dense(units = 9, activation = 'softmax'))

In [4]:
# Compiling the CNN
optimizer = keras.optimizers.Adam(learning_rate=0.001)
Model.compile(optimizer = optimizer, loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [5]:
from keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)

In [6]:
test_datagen = ImageDataGenerator(rescale = 1./255)

In [32]:
training_set = train_datagen.flow_from_directory('C:/Users/R. K Bokul/Desktop/Project_Face_Recognition/CNN_dataset/ORL_Database/',
                                                 target_size = (64, 64),
                                                 batch_size = 16,
                                                 class_mode = 'categorical')

Found 151 images belonging to 34 classes.


In [34]:
test_set = test_datagen.flow_from_directory('C:/Users/R. K Bokul/Desktop/Project_Face_Recognition/CNN_dataset/Test_data/',
                                            target_size = (64, 64),
                                            batch_size = 8,
                                            class_mode = 'categorical')

Found 41 images belonging to 9 classes.


In [35]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

# Define the model architecture
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(64, 64, 3)))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(5, activation='softmax'))

# Compile the model
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['accuracy'])


In [53]:
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
history = Model.fit(training_set, steps_per_epoch=151, epochs=5, validation_data=test_set, validation_steps=52)

Epoch 1/5


InvalidArgumentError: Graph execution error:

Detected at node 'categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):
    File "C:\ProgramData\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
      app.launch_new_instance()
    File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 846, in launch_instance
      app.start()
    File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
      self.io_loop.start()
    File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 199, in start
      self.asyncio_loop.run_forever()
    File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 601, in run_forever
      self._run_once()
    File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 1905, in _run_once
      handle._run()
    File "C:\ProgramData\Anaconda3\lib\asyncio\events.py", line 80, in _run
      self._context.run(self._callback, *self._args)
    File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
      await self.process_one()
    File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
      await dispatch(*args)
    File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
      await result
    File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
      reply_content = await reply_content
    File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 390, in do_execute
      res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
      return super().run_cell(*args, **kwargs)
    File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2914, in run_cell
      result = self._run_cell(
    File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2960, in _run_cell
      return runner(coro)
    File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
      coro.send(None)
    File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3185, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3377, in run_ast_nodes
      if (await self.run_code(code, result,  async_=asy)):
    File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3457, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "C:\Users\R. K Bokul\AppData\Local\Temp\ipykernel_12520\914424439.py", line 4, in <module>
      history = Model.fit(training_set, steps_per_epoch=162, epochs=15, validation_data=test_set, validation_steps=52)
    File "C:\Users\R. K Bokul\AppData\Roaming\Python\Python39\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\R. K Bokul\AppData\Roaming\Python\Python39\site-packages\keras\engine\training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\R. K Bokul\AppData\Roaming\Python\Python39\site-packages\keras\engine\training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "C:\Users\R. K Bokul\AppData\Roaming\Python\Python39\site-packages\keras\engine\training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\R. K Bokul\AppData\Roaming\Python\Python39\site-packages\keras\engine\training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "C:\Users\R. K Bokul\AppData\Roaming\Python\Python39\site-packages\keras\engine\training.py", line 1051, in train_step
      loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "C:\Users\R. K Bokul\AppData\Roaming\Python\Python39\site-packages\keras\engine\training.py", line 1109, in compute_loss
      return self.compiled_loss(
    File "C:\Users\R. K Bokul\AppData\Roaming\Python\Python39\site-packages\keras\engine\compile_utils.py", line 265, in __call__
      loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "C:\Users\R. K Bokul\AppData\Roaming\Python\Python39\site-packages\keras\losses.py", line 142, in __call__
      losses = call_fn(y_true, y_pred)
    File "C:\Users\R. K Bokul\AppData\Roaming\Python\Python39\site-packages\keras\losses.py", line 268, in call
      return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "C:\Users\R. K Bokul\AppData\Roaming\Python\Python39\site-packages\keras\losses.py", line 1984, in categorical_crossentropy
      return backend.categorical_crossentropy(
    File "C:\Users\R. K Bokul\AppData\Roaming\Python\Python39\site-packages\keras\backend.py", line 5565, in categorical_crossentropy
      return tf.nn.softmax_cross_entropy_with_logits(
Node: 'categorical_crossentropy/softmax_cross_entropy_with_logits'
logits and labels must be broadcastable: logits_size=[16,9] labels_size=[16,34]
	 [[{{node categorical_crossentropy/softmax_cross_entropy_with_logits}}]] [Op:__inference_train_function_2561]

In [48]:
filenames=test_set.filenames
nb_samples=len(filenames)
Y_pred = Model.predict(test_set, np.ceil(nb_samples/8))
y_pred = np.argmax(Y_pred, axis=1)
#print(Y_pred)
print('Confusion Matrix')
print(metrics.confusion_matrix(test_set.classes, y_pred))
print(metrics.accuracy_score(test_set.classes, y_pred))
print('Classification Report')
target_names = ['Liton', 'Siddique', 'Alomgir Ridoy', 'Toufique', 'Harun Badsha', 'Jakaria', 'Jamiul Islam', 'Juel', 'kanto']
print(classification_report(test_set.classes, y_pred, target_names=target_names))

#from skimage.io import imread
#from skimage.transform import resize
#import numpy as np
##
### Class labels
#class_labels = {v: k for k, v in training_set.class_indices.items()}
#class_labels
##
## reading the input image
#img = imread('data\\single_prediction\\1.jpg') 
#img = resize(img,(64,64)) 
#img = np.expand_dims(img,axis=0) 
#prediction = classifier.predict_classes(img)
#prediction


import numpy as np
from keras.preprocessing import image
from tensorflow.keras.preprocessing import image

test_image = image.load_img('C:/Users/R. K Bokul/Desktop/Project_Face_Recognition/CNN_dataset/1.jpg', target_size = (64, 64))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
result = Model.predict(test_image)
# result_1 = Model.predict_classes(test_image)
# result_1

training_set.class_indices
if result[0][0] == 1:
    prediction='Fahad Liton'
elif result[0][0] == 2:
    prediction='Siddique'
elif result[0][0] == 3:
    prediction='Alomgir Ridoy'
elif result[0][0] == 4:
    prediction='Toufique'
elif result[0][0] == 5:
    prediction='Harun Badsha'
elif result[0][0] == 6:
    prediction='Jakaria Rahman'
elif result[0][0] == 7:
    prediction='Jamiul'
elif result[0][0] == 8:
    prediction='Juel'
else:
    prediction='None'
print("The input image is: {0}".format(prediction))

6/6 [==============================] - 0s 27ms/step
Confusion Matrix
[[0 3 0 0 1 0 1 0 0]
 [0 0 0 0 1 0 1 0 0]
 [0 1 0 0 3 0 0 1 0]
 [0 4 0 0 1 0 0 0 0]
 [0 2 0 1 0 0 2 0 0]
 [0 4 0 0 0 0 1 0 0]
 [0 1 0 0 2 0 1 0 0]
 [0 2 0 0 2 0 1 0 0]
 [0 1 0 0 3 0 1 0 0]]
0.024390243902439025
Classification Report
               precision    recall  f1-score   support

        Liton       0.00      0.00      0.00         5
     Siddique       0.00      0.00      0.00         2
Alomgir Ridoy       0.00      0.00      0.00         5
     Toufique       0.00      0.00      0.00         5
 Harun Badsha       0.00      0.00      0.00         5
      Jakaria       0.00      0.00      0.00         5
 Jamiul Islam       0.12      0.25      0.17         4
         Juel       0.00      0.00      0.00         5
        kanto       0.00      0.00      0.00         5

     accuracy                           0.02        41
    macro avg       0.01      0.03      0.02        41
 weighted avg       0.01      0.02  

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
